name: skypi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.3.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  video_player: ^2.9.1
  flutter_pdfview: ^1.3.2
  dio: ^5.7.0
  open_filex: ^4.5.0
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  path: ^1.9.0
  firebase_storage: ^12.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
   - assets\google_logo.jpg